Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Shopping_Model.ViewModel;
using Online_Shopping_Web_Service.IService;

namespace Online_Shopping_Web.Controllers
{
    public class CategoryController : Controller
    {
		private readonly ICategoryWebService _service;
		public CategoryController(ICategoryWebService service)
		{
			_service = service;
		}
		public IActionResult GetCategoryList()
		{
			return View();
		}
		[HttpGet]
		public JsonResult CategoryList()
		{
			var category = _service.GetCategoryList();
			return new JsonResult(category);
		}
		public JsonResult GetCategoryById(int CategoryId)
		{
			var category = _service.GetCategoryById(CategoryId);
			return new JsonResult(category);
		}
		public JsonResult AddCategory(CategoryViewModel category)
		{
			var data = _service.AddCategory(category);
			return new JsonResult(data);
		}
		public JsonResult UpdateCategory(CategoryViewModel category)
		{
			var data = _service.UpdateCategory(category);
			return new JsonResult(data);
		}
		[HttpGet]
		public JsonResult DeleteCategory(int CategoryId)
		{
			var data = _service.DeleteCategory(CategoryId);
			return new JsonResult(data);
		}
	}
}

Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Online_Shopping_Model.ViewModel;
using Online_Shopping_Web_Service.IService;
using System.Net.Http;
using System.Net.Http.Headers;

namespace Online_Shopping_Web.Controllers
{
	//[Route("api/[controller]")]
	public class CustomerController : Controller
    {
		private readonly IHttpClientFactory _httpClientFactory;
		private readonly IWebHostEnvironment _environment;
        private readonly ICustomerWebService _service;

		HttpClient client = new HttpClient();
		public CustomerController(IHttpClientFactory httpClientFactory, ICustomerWebService service, IWebHostEnvironment environment)
        {
            _service = service;
            _environment= environment;
			_httpClientFactory = httpClientFactory;
        }
        public IActionResult GetCustomerList()
        {
            return View();
        }
        [HttpGet]
        public JsonResult CustomerList()
        {
            var customer = _service.GetAllCustomer();
            return new JsonResult(customer);
        }
        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View();
        }

		[HttpPost]
		public async Task<IActionResult> AddCustomer(CustomerViewModel customer, IFormFile PhotoPath)
		{
			using (var client = new HttpClient())
			{
				using (var content = new MultipartFormDataContent())
				{
					// Serialize the CustomerViewModel as JSON and add it to the request
					var customerJson = JsonConvert.SerializeObject(customer);
					content.Add(new StringContent(customerJson), "customer");

					if (PhotoPath != null && PhotoPath.Length > 0)
					{
						// Add the image file to the request
						content.Add(new StreamContent(PhotoPath.OpenReadStream()), "PhotoPath", PhotoPath.FileName);
					}

					var response = await client.PostAsync("http://localhost:5157/API/UploadImage", content);

					if (response.IsSuccessStatusCode)
					{
						return Ok("Customer data and image uploaded to API successfully.");
					}
				}
			}

			return BadRequest("Failed to upload customer data and image to API.");
		}



		[HttpPost]
		//public async Task<IActionResult> AddCustomer(CustomerViewModel customer, IFormFile PhotoPath)
		public async Task<IActionResult> ImageCustomer(CustomerViewModel customer, IFormFile PhotoPath)
		{

			if (PhotoPath != null && PhotoPath.Length > 0)
			{
				using (var client = new HttpClient())
				{
					using (var content = new MultipartFormDataContent())
					{
						content.Add(new StreamContent(PhotoPath.OpenReadStream()), "PhotoPath", PhotoPath.FileName);
						var response = await client.PostAsync("http://localhost:5157/API/UploadImage", content);
					}
				}
				return Ok("Image uploaded to API successfully.");
			}
			else
			{
				return BadRequest("Image upload to API failed.");
			}
		}

		//     [HttpPost]
		//     public JsonResult AddCustomer(CustomerViewModel customer, IFormFile PhotoPath)
		//     {
		//         string uniqueFileName = "";
		//if (PhotoPath != null)
		//{
		//	string fileName = Guid.NewGuid().ToString() + Path.GetExtension(PhotoPath.FileName);



		//	//string uploadFile = Path.Combine(_environment.WebRootPath, "Images/Customers");
		//	//uniqueFileName = Guid.NewGuid().ToString() + "_" + PhotoPath.FileName;
		//	//var filePath = Path.Combine(uploadFile, uniqueFileName);
		//	//using (var fileStream = new FileStream(filePath, FileMode.Create))
		//	//{
		//	//	PhotoPath.CopyTo(fileStream);
		//	//}
		//	customer.Photo = uniqueFileName;
		//}
		//var data = JsonConvert.SerializeObject(customer);
		//StringContent result = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
		//var res = client.PostAsync("http://localhost:5157/API/AddCustumer", result).Result;
		//return new JsonResult(res);
		//     }
		//public void UploadFile(IFormFile file,  a)


		// How to pass IFormFile image path from web controller to API controller solution asp.net core 6

		public JsonResult UpdateCustomer(CustomerViewModel customer, IFormFile PhotoPath)
        {
			string uniqueFileName = "";
			if (PhotoPath != null)
			{
				string fileName = Guid.NewGuid().ToString() + Path.GetExtension(PhotoPath.FileName);

				
				//string uploadFile = Path.Combine(_environment.WebRootPath, "Images/Customers");
				//uniqueFileName = Guid.NewGuid().ToString() + "_" + PhotoPath.FileName;
				//var filePath = Path.Combine(uploadFile, uniqueFileName);
				//using (var fileStream = new FileStream(filePath, FileMode.Create))
				//{
				//	PhotoPath.CopyTo(fileStream);
				//}
				customer.Photo = uniqueFileName;
			}
			var data = JsonConvert.SerializeObject(customer);
			StringContent result = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
			var res = client.PostAsync("http://localhost:5157/API/UpdateCustomer", result).Result;
			return new JsonResult(res);
		}

        [HttpGet]
        public JsonResult GetCustomerById(int CustomerId)
        {
            var data = _service.GetCustomerById(CustomerId);
            return new JsonResult(data);
        }
        [HttpGet]
        public JsonResult DeleteCustomer(int CustomerId)
        {
            var data = _service.DeleteCustomer(CustomerId);
            return new JsonResult(data);
        }
    }
}

Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Shopping_Model.ViewModel;
using Online_Shopping_Web_Service.IService;

namespace Online_Shopping_Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IProductWebService _service;
        public ProductController(IProductWebService service, IWebHostEnvironment environment)
        {
            _service = service;
            _environment = environment;
        }

		public IActionResult GetProducts()
		{
			var data = _service.GetProductList();
			return View(data);
		}
		public ActionResult Index()
        {
            return View();
        }
		public ActionResult GetProductList()
		{
			return View();
		}
		public JsonResult GetProduct()
        {
            var data = _service.GetProductList();
            return new JsonResult(data);
        }
        public IActionResult AddProduct(ProductImageViewModel product)
        {
            string uniqueFileName = "";
            if (product.PhotoPath != null)
            {
                string uploadFile = Path.Combine(_environment.WebRootPath, "Images/Products");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + product.PhotoPath.FileName;
                var filePath = Path.Combine(uploadFile, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.PhotoPath.CopyTo(fileStream);
                }
            }
            product.Photo = uniqueFileName;

            var data = _service.AddProduct(product);
            return new JsonResult(data);
        }


        public IActionResult UpdateProduct(ProductImageViewModel product)
        {
            string uniqueFileName = "";
            if (product.PhotoPath != null)
            {
                string uploadFile = Path.Combine(_environment.WebRootPath, "Images/Products");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + product.PhotoPath.FileName;
                var filePath = Path.Combine(uploadFile, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.PhotoPath.CopyTo(fileStream);
                }
            }
            product.Photo = uniqueFileName;

            var data = _service.UpdateProduct(product);
            return new JsonResult(data);
        }

        [HttpGet]
        public JsonResult GetProductById(int ProductId)
        {
            var data = _service.GetProductById(ProductId);
            return new JsonResult(data);
        }
        [HttpGet]
        public JsonResult DeleteProduct(int ProductId)
        {
            var data = _service.DeleteProduct(ProductId);
            return new JsonResult(data);
        }
        public IActionResult ProductDetail(int ProductId)
        {
			var data = _service.GetProductById(ProductId);
			return View(data);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/datatable/jquery.datatables.css" rel="stylesheet" />
	<link href="~/datatable/jquery.datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Online_Shopping_Web.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_Shopping_Web</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="AddCustomer">AddCustomer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="GetCategoryList">GetCategory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetProductList">GetProduct</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="GetCustomerList">GetCustomer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetProducts">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Online_Shopping_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/datatable/jquery.datatables.js"></script>
	<script src="~/datatable/jquery.datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>